# Assisted by watsonx Code Assistant
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

# Use the official Golang image as a builder
FROM golang:1.17 AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files first to leverage Docker cache
# COPY go.mod go.sum ./

# Download all dependencies
# RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Start a new stage from scratch
# FROM alpine:latest

# Set the Working Directory in the new stage
# WORKDIR /root/

# Copy the binary file from the previous stage
# COPY --from=builder /app/main .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the executable
CMD ["./main"]



